tags:
  kafka: false
  backup: true
  cockroach: true
  naughtybot: false
  botscribe: false
  scratchbot: false
  scribble: true
  dean: true

kafkabrokers: &kb "kafka-headless.default.svc.cluster.local:29092"
chatTopic: &topic "vlab-prod-chat-events"
stateTopic: &statetopic "vlab-prod-state"
responseTopic: &responsetopic "vlab-prod-response"
paymentTopic: &paymenttopic "vlab-prod-payment"
botEnvs: &botenvs gbv-bot-envs
chatbaseHost: &host "gbv-cockroachdb-public"


versionDashboard: &vdashboard v0.0.27
versionBotserver: &vbotserver 0.0.9
versionReplybot: &vreplybot v0.0.126
versionLinksniffer: &vlinksniffer v0.0.4
versionDean: &vdean v0.0.24
versionScribble: &vscribble v0.0.21
versionDinersclub: &vdinersclub v0.0.19
versionFormcentral: &vformcentral v0.0.8

processingAlerts:
  - consumergroup: replybot
    topic: *topic
    window: "8h"
    limit: "1"

laggingAlerts:
  - consumergroup: replybot
    alertname: LaggingConsumerReplybot
    window: "5m"
    limit: "20"
  - consumergroup: scribble-responses
    alertname: LaggingConsumerScribbleResponses
    window: "5m"
    limit: "200"
  - consumergroup: scribble-states
    alertname: LaggingConsumerScribbleStates
    window: "5m"
    limit: "200"
  - consumergroup: scribble-messages
    alertname: LaggingConsumerScribbleMessages
    window: "5m"
    limit: "200"
  - consumergroup: dinersclub
    alertname: LaggingConsumerDinersclub
    window: "5m"
    limit: "100"

kafkaTopics:
  - name: *topic
    partitions: 48
    replicationFactor: 3
    config:
      "retention.ms": "2678400000" # 31 days
  - name: *statetopic
    partitions: 12
    replicationFactor: 3
    config:
      "retention.ms": "2678400000" # 31 days
  - name: *responsetopic
    partitions: 12
    replicationFactor: 3
    config:
      "retention.ms": "2678400000" # 31 days
  - name: *paymenttopic
    partitions: 2
    replicationFactor: 3
    config:
      "retention.ms": "2678400000" # 31 days


dinersclub:
  replicaCount: 1
  image:
    repository: vlabresearch/dinersclub
    tag: *vdinersclub
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 5m
      memory: 16Mi
  envFrom: gbv-bot-envs
  env:
    - name: CACHE_TTL
      value: "1h"
    - name: CACHE_NUM_COUNTERS
      value: "1000"
    - name: CACHE_MAX_COST
      value: "1000"
    - name: CACHE_BUFFER_ITEMS
      value: "64"
    - name: RELOADLY_SANDBOX
      value: "false"
    - name: BOTSERVER_URL
      value: "http://gbv-botserver/synthetic"
    - name: CHATBASE_DATABASE
      value: "chatroach"
    - name: CHATBASE_HOST
      value: *host
    - name: CHATBASE_PORT
      value: "26257"
    - name: CHATBASE_USER
      value: "chatroach"
    - name: CHATBASE_MAX_CONNECTIONS
      value: "1"
    - name: KAFKA_BROKERS
      value: *kb
    - name: KAFKA_POLL_TIMEOUT
      value: "10s"
    - name: KAFKA_TOPIC
      value: *paymenttopic
    - name: KAFKA_GROUP
      value: "dinersclub"
    - name: DINERSCLUB_BATCH_SIZE
      value: "8"
    - name: DINERSCLUB_RETRY_BOTSERVER
      value: "2m"
    - name: DINERSCLUB_RETRY_PROVIDER
      value: "2m"
    - name: DINERSCLUB_POOL_SIZE
      value: "8"
    - name: DINERSCLUB_PROVIDERS
      value: "fake,reloadly,giftcard"

dean:
  image:
    repository: vlabresearch/dean
    tag: *vdean
    pullPolicy: IfNotPresent
  env:
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  - name: BOTSERVER_URL
    value: "http://gbv-botserver/synthetic"
  - name: DEAN_ERROR_TAGS
    value: "NETWORK,INTERNAL,STATE_ACTIONS"
  - name: DEAN_ERROR_INTERVAL
    value: "24 hours"
  - name: DEAN_FB_CODES
    value: "2022,613,-1,190,80006"
  - name: DEAN_BLOCKED_INTERVAL
    value: "24 hours"
  - name: DEAN_RESPONDING_INTERVAL
    value: "24 hours"
  - name: DEAN_RESPONDING_GRACE
    value: "20 minutes"
  - name: DEAN_SEND_DELAY
    value: "3s"
  - name: DEAN_FOLLOWUP_MIN
    value: "6 hours"
  - name: DEAN_FOLLOWUP_MAX
    value: "24 hours"
  queries:
    - name: respondings
      queries: "respondings,blocked,errored"
      schedule: "*/30 * * * *"
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
    - name: followups
      queries: "followups"
      schedule: "0 5-19 * * *"
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
    - name: timeouts
      queries: "timeouts"
      schedule: "*/10 * * * *"
      resources:
        requests:
          cpu: 10m
          memory: 10Mi

scribble:
  image:
    repository: vlabresearch/scribble
    tag: *vscribble
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 15m
      memory: 64Mi
  env:
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  - name: KAFKA_BROKERS
    value: *kb
  - name: KAFKA_POLL_TIMEOUT
    value: "2s"
  - name: SCRIBBLE_ERROR_HANDLERS
    value: ""

  sinks:
    - destination: "states"
      replicaCount: 1
      env:
      - name: KAFKA_TOPIC
        value: *statetopic
      - name: KAFKA_GROUP
        value: "scribble-states"
      - name: SCRIBBLE_CHUNK_SIZE
        value: "128"
      - name: SCRIBBLE_BATCH_SIZE
        value: "128"
    - destination: "responses"
      replicaCount: 1
      env:
      - name: KAFKA_TOPIC
        value: *responsetopic
      - name: KAFKA_GROUP
        value: "scribble-responses"
      - name: SCRIBBLE_CHUNK_SIZE
        value: "32"
      - name: SCRIBBLE_BATCH_SIZE
        value: "64"
    - destination: "messages"
      replicaCount: 1
      env:
      - name: KAFKA_TOPIC
        value: *topic
      - name: KAFKA_GROUP
        value: "scribble-messages"
      - name: SCRIBBLE_CHUNK_SIZE
        value: "32"
      - name: SCRIBBLE_BATCH_SIZE
        value: "128"

dumper:
  image:
    repository: vlabresearch/dumper
    tag: 0.0.11
    pullPolicy: IfNotPresent

  completions: 1
  parallelism: 1
  backoffLimit: 8

  schedule: "30 0 * * *"
  resources:
    requests:
      cpu: 750m
      memory: 300Mi

  keySecret: gbv-dumper-keys
  env:
  - name: CHATBASE_HOST
    value: *host
  - name: DUMPER_LOCATION
    value: "gs://vlab-research-backups/gbv-india/"

formcentral:
  replicaCount: 1
  image:
    tag: *vformcentral
  env:
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  - name: CHATBASE_MAX_CONNECTIONS
    value: "6"
  - name: PORT
    value: "1323"
  resources:
    requests:
      cpu: 10m
      memory: 10Mi


linksniffer:
  replicaCount: 2

  image:
    repository: vlabresearch/linksniffer
    tag: *vlinksniffer
    pullPolicy: IfNotPresent

  env:
  - name: BOTSERVER_URL
    value: "http://gbv-botserver/synthetic"

  resources:
    requests:
      cpu: 5m
      memory: 10Mi

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: links.vlab.digital
        paths:
          - "/"
    tls:
      - secretName: gbv-linksniffer-cert
        hosts:
          - links.vlab.digital

  service:
    type: ClusterIP
    port: 80

dashboard:
  replicaCount: 3

  image:
    repository: vlabresearch/dashboard
    tag: *vdashboard
    pullPolicy: IfNotPresent

  envFrom: *botenvs
  env:
    - name: FAKE
      value: 'nope'
    - name: TYPEFORM_URL
      value: 'https://api.typeform.com'
    - name: CUBEJS_API_SECRET
      value: 'notasecret'
    - name: CUBEJS_DB_TYPE
      value: 'postgres'
    - name: DB_DATABASE
      value: 'chatroach'
    - name: CUBEJS_DB_NAME
      value: 'chatroach'
    - name: DB_USER
      value: 'chatroach'
    - name: CUBEJS_DB_USER
      value: 'chatroach'
    - name: DB_PASSWORD
      value: ''
    - name: CUBEJS_DB_PASS
      value: ''
    - name: DB_HOST
      value: *host
    - name: CUBEJS_DB_HOST
      value: *host
    - name: DB_PORT
      value: '26257'
    - name: CUBEJS_DB_PORT
      value: '26257'
    - name: FORMCENTRAL_URL
      value: 'http://gbv-formcentral'
    - name: TYPEFORM_REDIRECT_URL
      value: 'https://app.vlab.digital/surveys/auth'
    - name: FACEBOOK_GRAPH_URL
      value: 'https://graph.facebook.com/v9.0'

  resources:
    requests:
      cpu: 10m
      memory: 80Mi

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: gbv-dashboard.nandan.cloud
        paths:
          - '/'
    tls:
      - secretName: gbv-dashboard-cert
        hosts:
          - gbv-dashboard.nandan.cloud

  service:
    type: ClusterIP
    port: 80


replybot:
  replicaCount: 12
  image:
    repository: vlabresearch/replybot
    tag: *vreplybot
    pullPolicy: IfNotPresent

  envFrom: *botenvs
  resources:
    requests:
      cpu: 15m
      memory: 100Mi
  env:
  - name: FAKE
    value: "NOTHIN"
  - name: CHATBASE_BACKEND
    value: "@vlab-research/chatbase-postgres"
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  - name: FALLBACK_FORM
    value: "305"
  - name: REPLYBOT_EVENT_TOPIC
    value: *topic
  - name: BOTSPINE_KAFKA_BROKERS
    value: *kb
  - name: KAFKA_BROKERS
    value: *kb
  - name: BOTSPINE_MESSAGE_TOPIC
    value: *topic
  - name: VLAB_STATE_TOPIC
    value: *statetopic
  - name: VLAB_RESPONSE_TOPIC
    value: *responsetopic
  - name: VLAB_PAYMENT_TOPIC
    value: *paymenttopic
  - name: BOTSERVER_URL
    value: "http://gbv-botserver"
  - name: FACEBOOK_GRAPH_URL
    value: "https://graph.facebook.com/v11.0"
  - name: FORMCENTRAL_URL
    value: "http://gbv-formcentral"

botserver:
  replicaCount: 3

  image:
    repository: vlabresearch/botserver
    tag: *vbotserver
    pullPolicy: IfNotPresent

  envFrom: *botenvs

  env:
  - name: BOTSERVER_EVENT_TOPIC
    value: *topic
  - name: KAFKA_BROKERS
    value: *kb
  - name: PORT
    value: "80"

  resources:
    requests:
      cpu: 5m
      memory: 48Mi

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: gbvbot.nandan.cloud
        paths:
          - "/"
    tls:
      - secretName: gbv-botserver-cert
        hosts:
          - gbvbot.nandan.cloud

  service:
    type: ClusterIP
    port: 80


cockroachdb:
  image:
    tag: v20.1.4
  statefulset:
    replicas: 4
    resources:
      requests:
        cpu: 200m
        memory: 8000Mi
  conf:
    cache: 3500Mi
    max-sql-memory: 3000Mi
    max-disk-temp-storage: 24GiB
    budget:
      maxUnavailable: 1
  tls:
    enabled: no
  storage:
    persistentVolume:
      size: 100Gi
      storageClass: "pd-ssd"
