tags:
  kafka: false
  backup: true
  cockroach: true
  naughtybot: false
  botscribe: false
  scratchbot: false
  scribble: true
  dean: true

kafkabrokers: &kb "kafka-headless.default.svc.cluster.local:29092"
chatTopic: &topic "vlab-staging-chat-events"
stateTopic: &statetopic "vlab-staging-state"
responseTopic: &responsetopic "vlab-staging-response"
paymentTopic: &paymenttopic "vlab-staging-payment"
botEnvs: &botenvs gbv-bot-envs
chatbaseHost: &host "gbv-cockroachdb-public"

versionDashboard: &vdashboard 0.0.25
versionBotserver: &vbotserver 0.0.9
versionReplybot: &vreplybot v0.0.125
versionLinksniffer: &vlinksniffer v0.0.4
versionDean: &vdean v0.0.24
versionScribble: &vscribble 0.0.20
versionDinersclub: &vdinersclub v0.0.10
versionFormcentral: &vformcentral v0.0.6

processingAlerts: []
laggingAlerts: []

kafkaTopics:
  - name: *topic
    partitions: 8
    replicationFactor: 3
    config:
      "retention.ms": "2678400000" # 31 days
  - name: *statetopic
    partitions: 2
    replicationFactor: 2
    config:
      "retention.ms": "2678400000" # 31 days
  - name: *responsetopic
    partitions: 2
    replicationFactor: 2
    config:
      "retention.ms": "2678400000" # 31 days
  - name: *paymenttopic
    partitions: 2
    replicationFactor: 2
    config:
      "retention.ms": "2678400000" # 31 days


dinersclub:
  image:
    repository: vlabresearch/dinersclub
    tag: *vdinersclub
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 5m
      memory: 16Mi
  envFrom: gbv-bot-envs
  env:
    - name: BOTSERVER_URL
      value: "http://gbv-botserver/synthetic"
    - name: KAFKA_BROKERS
      value: *kb
    - name: KAFKA_TOPIC
      value: *paymenttopic
    - name: KAFKA_GROUP
      value: "dinersclub"
    - name: KAFKA_POLL_TIMEOUT
      value: "2s"
    - name: DINERSCLUB_RETRY_BOTSERVER
      value: "2m"
    - name: DINERSCLUB_RETRY_PROVIDER
      value: "2m"
    - name: DINERSCLUB_PROVIDERS
      value: "fake,reloadly"
    - name: DINERSCLUB_POOL_SIZE
      value: "1"
    - name: DINERSCLUB_BATCH_SIZE
      value: "1"
    - name: RELOADLY_SANDBOX
      value: "true"


dean:
  image:
    repository: vlabresearch/dean
    tag: *vdean
    pullPolicy: IfNotPresent
  env:
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  - name: BOTSERVER_URL
    value: "http://gbv-botserver/synthetic"
  - name: DEAN_ERROR_TAGS
    value: "NETWORK,INTERNAL"
  - name: DEAN_ERROR_INTERVAL
    value: "24 hours"
  - name: DEAN_FB_CODES
    value: "2022,-1"
  - name: DEAN_BLOCKED_INTERVAL
    value: "24 hours"
  - name: DEAN_RESPONDING_INTERVAL
    value: "23 hours"
  - name: DEAN_RESPONDING_GRACE
    value: "1 hour"
  - name: DEAN_SEND_DELAY
    value: "1s"
  - name: DEAN_FOLLOWUP_MIN
    value: "2 minutes"
  - name: DEAN_FOLLOWUP_MAX
    value: "24 hours"
  queries:
    - name: respondings
      queries: "respondings,blocked,errored"
      schedule: "*/1 * * * *"
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
    - name: timeouts
      queries: "timeouts,followups"
      schedule: "*/1 * * * *"
      resources:
        requests:
          cpu: 10m
          memory: 10Mi

scribble:
  image:
    repository: vlabresearch/scribble
    tag: *vscribble
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 40m
      memory: 64Mi
  env:
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  - name: KAFKA_BROKERS
    value: *kb
  - name: KAFKA_POLL_TIMEOUT
    value: "10s"
  - name: SCRIBBLE_CHUNK_SIZE
    value: "16"
  - name: SCRIBBLE_BATCH_SIZE
    value: "16"
  - name: SCRIBBLE_ERROR_HANDLERS
    value: ""

  sinks:
    - destination: "states"
      replicaCount: 1
      env:
      - name: KAFKA_TOPIC
        value: *statetopic
      - name: KAFKA_GROUP
        value: "scribble-states"

    - destination: "responses"
      replicaCount: 1
      env:
      - name: KAFKA_TOPIC
        value: *responsetopic
      - name: KAFKA_GROUP
        value: "scribble-responses"

    - destination: "messages"
      replicaCount: 1
      env:
      - name: KAFKA_TOPIC
        value: *topic
      - name: KAFKA_GROUP
        value: "scribble-messages"


dumper:
  image:
    repository: vlabresearch/dumper
    tag: 0.0.1
    pullPolicy: IfNotPresent

  completions: 1
  parallelism: 1
  backoffLimit: 3

  schedule: "10 11 * * *"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

  keySecret: gbv-dumper-keys
  env:
  - name: CHATBASE_HOST
    value: *host
  - name: DUMPER_LOCATION
    value: "gs://vlab-research-backups/gbv-india-staging/"


replybot:
  replicaCount: 1
  image:
    repository: vlabresearch/replybot
    tag: *vreplybot
    pullPolicy: IfNotPresent

  envFrom: *botenvs
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
  env:
  - name: CHATBASE_BACKEND
    value: "@vlab-research/chatbase-postgres"
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  - name: FALLBACK_FORM
    value: "305"
  - name: REPLYBOT_EVENT_TOPIC
    value: *topic
  - name: BOTSPINE_KAFKA_BROKERS
    value: *kb
  - name: KAFKA_BROKERS
    value: *kb
  - name: BOTSPINE_MESSAGE_TOPIC
    value: *topic
  - name: VLAB_STATE_TOPIC
    value: *statetopic
  - name: VLAB_RESPONSE_TOPIC
    value: *responsetopic
  - name: VLAB_PAYMENT_TOPIC
    value: *paymenttopic
  - name: DASHBOARD_API
    value: "http://gbv-dashboard/api/v1"
  - name: BOTSERVER_URL
    value: "http://gbv-botserver"
  - name: FACEBOOK_GRAPH_URL
    value: "https://graph.facebook.com/v8.0"

formcentral:
  replicaCount: 1
  image:
    tag: *vformcentral
  env:
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  resources:
    requests:
      cpu: 10m
      memory: 10Mi

linksniffer:
  replicaCount: 1

  image:
    repository: vlabresearch/linksniffer
    tag: *vlinksniffer
    pullPolicy: IfNotPresent

  env:
  - name: BOTSERVER_URL
    value: "http://gbv-botserver/synthetic"

  resources:
    requests:
      cpu: 10m
      memory: 50Mi

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: gbvlinks-staging.nandan.cloud
        paths:
          - "/"
    tls:
      - secretName: gbv-linksniffer-cert
        hosts:
          - gbvlinks-staging.nandan.cloud

  service:
    type: ClusterIP
    port: 80

dashboard:
  replicaCount: 1

  image:
    repository: vlabresearch/dashboard
    tag: *vdashboard
    pullPolicy: IfNotPresent

  envFrom: *botenvs
  env:
    - name: TYPEFORM_URL
      value: 'https://api.typeform.com'
    - name: CUBEJS_API_SECRET
      value: 'notasecret'
    - name: CUBEJS_DB_TYPE
      value: 'postgres'
    - name: DB_DATABASE
      value: 'chatroach'
    - name: CUBEJS_DB_NAME
      value: 'chatroach'
    - name: DB_USER
      value: 'chatroach'
    - name: CUBEJS_DB_USER
      value: 'chatroach'
    - name: DB_PASSWORD
      value: ''
    - name: CUBEJS_DB_PASS
      value: ''
    - name: DB_HOST
      value: *host
    - name: CUBEJS_DB_HOST
      value: *host
    - name: DB_PORT
      value: '26257'
    - name: CUBEJS_DB_PORT
      value: '26257'
    - name: TYPEFORM_REDIRECT_URL
      value: 'https://staging--vlab-research.netlify.app/surveys/auth'
    - name: FORMCENTRAL_URL
      value: 'http://gbv-formcentral'
    - name: FACEBOOK_GRAPH_URL
      value: 'https://graph.facebook.com/v9.0'

  resources:
    requests:
      cpu: 10m
      memory: 64Mi

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: gbv-dashboard-staging.nandan.cloud
        paths:
          - '/'
    tls:
      - secretName: gbv-dashboard-cert
        hosts:
          - gbv-dashboard-staging.nandan.cloud

  service:
    type: ClusterIP
    port: 80


botserver:
  replicaCount: 1

  image:
    repository: vlabresearch/botserver
    tag: *vbotserver
    pullPolicy: IfNotPresent

  envFrom: *botenvs

  env:
  - name: BOTSERVER_EVENT_TOPIC
    value: *topic
  - name: KAFKA_BROKERS
    value: *kb
  - name: PORT
    value: "80"

  resources:
    requests:
      cpu: 10m
      memory: 128Mi

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: gbvbot-staging.nandan.cloud
        paths:
          - "/"
    tls:
      - secretName: gbv-botserver-cert
        hosts:
          - gbvbot-staging.nandan.cloud

  service:
    type: ClusterIP
    port: 80


cockroachdb:
  image:
    tag: v20.1.4
  statefulset:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
  conf:
    cache: 250MiB
    max-sql-memory: 250MiB
    max-disk-temp-storage: 4GiB
    budget:
      maxUnavailable: 0
  tls:
    enabled: no
  storage:
    persistentVolume:
      size: 5Gi
      storageClass: "pd-ssd"
