apiVersion: v2
name: vlab
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
dependencies:
  - name: replybot
    version: 0.0.1
    repository: https://vlab-research.github.io/fly
  - name: botserver
    version: 0.0.1
    repository: https://vlab-research.github.io/fly
  - name: linksniffer
    version: 0.0.1
    repository: https://vlab-research.github.io/fly
  - name: dashboard
    version: 0.0.1
    repository: https://vlab-research.github.io/fly
  - name: formcentral
    version: 0.0.1
    repository: https://vlab-research.github.io/fly
  - name: dumper
    version: 0.0.1
    repository: https://vlab-research.github.io/fly
    tags:
      - backup
  - name: dinersclub
    version: 0.0.1
    repository: https://vlab-research.github.io/fly
    tags:
      - payments
  - name: dean
    version: 0.0.2
    repository: https://vlab-research.github.io/fly
    tags:
      - dean
  - name: scribble
    version: 0.0.1
    repository: https://vlab-research.github.io/fly
    tags:
      - scribble
  - name: naughtybot
    version: 0.0.1
    repository: https://vlab-research.github.io/fly
    tags:
      - naughtybot
  - name: botscribe
    version: 0.0.1
    repository: https://vlab-research.github.io/fly
    tags:
      - botscribe
  - name: scratchbot
    version: 0.0.1
    repository: https://vlab-research.github.io/fly
    tags:
      - scratchbot

# TODO: move database out of here (treat as provider)
# add init job to create database and users
  - name: cockroachdb
    version: 5.0.1
    repository: https://charts.cockroachdb.com/
    tags:
      - cockroach

  - name: kafka
    version: 14.0.5
    repository: https://charts.bitnami.com/bitnami
    tags:
      - kafka
