apiVersion: batch/v1
kind: Job
metadata:
  name: gbv-testrunner
  labels:
    app: gbv-testrunner
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: gbv-testrunner
    spec:
      restartPolicy: OnFailure
      containers:
      - name: gbv-testrunner
        image: vlabresearch/testrunner:v0.0.3
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "10m"
            memory: "30Mi"
        ports:
        - containerPort: 88
        envFrom:
        - secretRef:
            name: gbv-bot-envs
        env:
        - name: BOTSERVER_URL
          value: "http://gbv-botserver"
        - name: KAFKA_BROKERS
          value: "gbv-kafka:9092"
        - name: CHATBASE_BACKEND
          value: "@vlab-research/chatbase-postgres"
        - name: CHATBASE_DATABASE
          value: "chatroach"
        - name: CHATBASE_USER
          value: "chatroach"
        - name: CHATBASE_PASSWORD
          value: ""
        - name: CHATBASE_HOST
          value: "gbv-cockroachdb-public"
        - name: CHATBASE_PORT
          value: "26257"
